### ISSUE TITLE
Cannot sign up, certificate expired

### ISSUE THREAD

**Issue by blubberdiblub** [jacogrande/codactor-web#2]
I'm unable to sign up on the web site.
After entering my sign up details and clicking the Sign Up button, it says "certificate expired" in red below.

(Btw, if it was a Let's Encrypt certificate, those certificates expire after 3 months because the idea is to have an automated process renew them every month or so. "certbot" is the tool you want to set up to run regularly for it to renew your certificates automatically.)

**Comment by ZMobile** [comment]
Hi Blubberdiblub,

Thank you for reporting this issue. It’s true we’ve been dealing with this certificate problem periodically manually, perhaps we should set up something automated to renew it. We’ll look into that and at the very least see about renewing the certificate for now. I’ll close this issue once that’s done so you get a notification.

**Comment by ZMobile** [comment]
The temporary issue at least has been resolved, we’ll work on some automated renewal system in order to prevent this issue from popping up again. Thanks again for reaching out about this, feel free to report here if you encounter any other bugs or issues.
Enjoy Codactor!
