### ISSUE TITLE
Certificate expired during sign up still not resolved

### ISSUE THREAD

**Issue by blubberdiblub** [jacogrande/codactor-web#3]
Unfortunately, the immediate user facing issue (#2) still doesn't appear to be resolved. It still displays the message "certificate has expired" and doesn't proceed with the sign up process:

![image](https://github.com/jacogrande/codactor-web/assets/69097/6c4c8428-037f-4319-a77a-cb796ee56b50)

**Comment by ZMobile** [comment]
My apologies, I actually had a miscommunication moment with my web developer @jacogrande (I work on the backend) leading to me prematurely closing this issue. He communicated that the website updates are live but was only referring to new visual changes.

Issue is reopened, he said he’ll take care of the certificate issue hopefully today still and I’ll keep you informed. Apologies again, issue wasn’t fixed in the first place.

**Comment by blubberdiblub** [comment]
No worries and no pressure, personally I don't mind the timeframe. Signing up will still be there tomorrow or the day after, so it'll be fine whenever. 😸

**Comment by blubberdiblub** [comment]
Btw, I noticed that it comes around with a different error now: "self-signed certificate"

If you allow me to take an educated guess, I'd say the problem you're presented with is that the user-facing web server is talking to an isolated machine or container for the user credentials. And setting up a working _certbot_ to renew the certificates on that isolated machine/container probably proves difficult because of the verification process required and you don't want to open a listening port to the outside for security reasons (which is understandable).

The way we did it at the place I used to work was to set up a dedicated container for certificate renewal and distribution that had _certbot_ running. And then we configured the _certbot_ hooks to distribute the certificates to all other machines/containers that needed them via _scp_ (restricted with owner/group permissions, so _certbot_ was only allowed to update certificate related files and nothing else). _rsync_ would work, too, as would a pull setup (machines/containers scp'ing certificates from the cert box/container to themselves in regular time intervals) instead of our push setup.

Hope this info helps somewhat. If it doesn't, that's also fine and in that case just regard this post as noise ;)

**Comment by blubberdiblub** [comment]
Oh, and it should also be possible to make the self-signed certificate work, if you prefer that route. I think it just amounts to giving the web server's process that connects to the isolated machine/container (whichever process that is, you know, something like php-fpm, uwsgi, gunicorn, django, node.js, etc.) the self-signed certificate (without the private key) as a CA (possibly in addition to the standard CAs; and as the CA which verifies servers, not the other CA that verifies client certificates) to verify the certificate against. Sounds a bit funny, but that should usually work.

**Comment by ZMobile** [comment]
That’s a solid idea actually, I’ll definitely keep that in mind for the automated certificate renewal system, though I will say we don’t generally have a problem with exposing endpoints to the public if they have proper backend security in place for the scenario such as spring security etc.

The reality is we tried a different/new method this time around generating a certificate managed by google cloud’s service, but that didn’t work out as it failed to provision so I essentially took the certificate signing and such into my own hands like last time and decided to go with the manual certbot method, just in the interest of getting it working here as the downtime has definitely irked me but I’ve been too busy to really handle it until now.

In any case I did the process a bit incorrectly last night but it was late so I left it as such, looking to fix the problem today. I appreciate your patience, again sorry for the downtime we’ll work on making this not a problem in the future. New certificate storing methods should really be tried not after our current one has expired.

**Comment by ZMobile** [comment]
The issue has now been fixed for real this time, temporarily. Thank you again for your patience, and please let me know if you run into any other issues.

**Comment by nafg** [comment]
I'm getting this :(

**Comment by ZMobile** [comment]
Hi @nafg thank you for reporting this. We are currently facing technical difficulties renewing our certificates this time around due to recent domain provider changes, we will be attempting to fix this issue as soon as possible.

**Comment by ZMobile** [comment]
Apologies for the extensive delay. We have finally gotten around to figuring out how to renew this certificate following the domain transfer, so it should not be an issue in the future. Again I apologize for the excessive delay.

We are currently working to renovate this service for proper public use.
